CREATE TABLE IF NOT EXISTS category (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name text
);
COMMENT ON TABLE category IS '행사 카테고리 종류 데이터 베이스';

CREATE TABLE IF NOT EXISTS gu (
    gu_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gu_name varchar
);
COMMENT ON TABLE gu IS '서울시 내 구 데이터 베이스';

INSERT INTO category (category_id, category_name) VALUES
    (1, '교육/체험'),
    (2, '국악'),
    (3, '독주/독창회'),
    (4, '무용'),
    (5, '뮤지컬/오페라'),
    (6, '연극'),
    (7, '영화'),
    (8, '전시/미술'),
    (9, '축제-기타'),
    (10, '축제-문화/예술'),
    (11, '축제-시민화합'),
    (12, '축제-자연/경관'),
    (13, '축제-전통/역사'),
    (14, '콘서트'),
    (15, '클래식'),
    (16, '기타')
ON CONFLICT (category_id) DO UPDATE SET category_name = EXCLUDED.category_name;

INSERT INTO gu (gu_id, gu_name) VALUES
    (1, '강북구'),
    (2, '강남구'),
    (3, '강동구'),
    (4, '강서구'),
    (5, '관악구'),
    (6, '광진구'),
    (7, '구로구'),
    (8, '금천구'),
    (9, '노원구'),
    (10, '도봉구'),
    (11, '동대문구'),
    (12, '동작구'),
    (13, '마포구'),
    (14, '서대문구'),
    (15, '서초구'),
    (16, '성동구'),
    (17, '성북구'),
    (18, '송파구'),
    (19, '양천구'),
    (20, '영등포구'),
    (21, '용산구'),
    (22, '은평구'),
    (23, '종로구'),
    (24, '중구'),
    (25, '중랑구'),
    (26, '경기도 과천시')
ON CONFLICT (gu_id) DO UPDATE SET gu_name = EXCLUDED.gu_name;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_category_seq_fkey') THEN
        ALTER TABLE events
            ADD CONSTRAINT events_category_seq_fkey
            FOREIGN KEY (category_seq) REFERENCES category(category_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_gu_seq_fkey') THEN
        ALTER TABLE events
            ADD CONSTRAINT events_gu_seq_fkey
            FOREIGN KEY (gu_seq) REFERENCES gu(gu_id);
    END IF;
END $$;

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE category ENABLE ROW LEVEL SECURITY;
ALTER TABLE gu ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'events' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON events FOR SELECT TO public USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'category' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON category FOR SELECT TO public USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'gu' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON gu FOR SELECT TO public USING (true);
    END IF;
END $$;

CREATE OR REPLACE FUNCTION public.import_events_batch(payload jsonb)
RETURNS integer
LANGUAGE sql
AS $function$
  WITH base AS (
    SELECT COALESCE(MAX(event_id), 0) AS max_id FROM public.events
  ), raw AS (
    SELECT elem, ord
    FROM jsonb_array_elements(payload) WITH ORDINALITY AS t(elem, ord)
  ), ins AS (
    INSERT INTO public.events (
      event_id, category_seq, gu_seq, event_name, period, place, org_name, use_target,
      ticket_price, inqury_number, player, describe, etc_desc, homepage_link, main_img,
      reg_date, is_public, start_date, end_date, theme, latitude, longitude, is_free,
      detail_url, display_time, geohash
    )
    SELECT
      base.max_id + raw.ord,
      (elem->>'category_seq')::bigint,
      (elem->>'gu_seq')::bigint,
      elem->>'event_name', elem->>'period', elem->>'place', elem->>'org_name', elem->>'use_target',
      elem->>'ticket_price', elem->>'inqury_number', elem->>'player', elem->>'describe', elem->>'etc_desc',
      elem->>'homepage_link', elem->>'main_img', (elem->>'reg_date')::timestamptz,
      (elem->>'is_public')::boolean, (elem->>'start_date')::timestamptz, (elem->>'end_date')::timestamptz,
      elem->>'theme', (elem->>'latitude')::double precision, (elem->>'longitude')::double precision,
      (elem->>'is_free')::boolean, elem->>'detail_url', elem->>'display_time', elem->>'geohash'
    FROM raw CROSS JOIN base
    ORDER BY raw.ord
    RETURNING 1
  )
  SELECT count(*)::integer FROM ins;
$function$;

CREATE OR REPLACE FUNCTION public.import_events_batch_with_start(payload jsonb, start_id bigint)
RETURNS integer
LANGUAGE sql
AS $function$
  WITH raw AS (
    SELECT elem, ord
    FROM jsonb_array_elements(payload) WITH ORDINALITY AS t(elem, ord)
  ), ins AS (
    INSERT INTO public.events (
      event_id, category_seq, gu_seq, event_name, period, place, org_name, use_target,
      ticket_price, inqury_number, player, describe, etc_desc, homepage_link, main_img,
      reg_date, is_public, start_date, end_date, theme, latitude, longitude, is_free,
      detail_url, display_time, geohash
    )
    SELECT
      start_id + raw.ord - 1,
      (elem->>'category_seq')::bigint,
      (elem->>'gu_seq')::bigint,
      elem->>'event_name', elem->>'period', elem->>'place', elem->>'org_name', elem->>'use_target',
      elem->>'ticket_price', elem->>'inqury_number', elem->>'player', elem->>'describe', elem->>'etc_desc',
      elem->>'homepage_link', elem->>'main_img', (elem->>'reg_date')::timestamptz,
      (elem->>'is_public')::boolean, (elem->>'start_date')::timestamptz, (elem->>'end_date')::timestamptz,
      elem->>'theme', (elem->>'latitude')::double precision, (elem->>'longitude')::double precision,
      (elem->>'is_free')::boolean, elem->>'detail_url', elem->>'display_time', elem->>'geohash'
    FROM raw
    ORDER BY raw.ord
    RETURNING 1
  )
  SELECT count(*)::integer FROM ins;
$function$;
