ALTER TABLE events DROP CONSTRAINT IF EXISTS events_category_seq_fkey;
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_gu_seq_fkey;
DROP INDEX IF EXISTS events_source_unique_idx;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'category' AND column_name = 'seq'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'category' AND column_name = 'category_id'
    ) THEN
        ALTER TABLE category RENAME COLUMN seq TO category_id;
        ALTER TABLE category RENAME COLUMN name TO category_name;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'gu' AND column_name = 'seq'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'gu' AND column_name = 'gu_id'
    ) THEN
        ALTER TABLE gu RENAME COLUMN seq TO gu_id;
        ALTER TABLE gu RENAME COLUMN name TO gu_name;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'events' AND column_name = 'inquiry_number'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'events' AND column_name = 'inqury_number'
    ) THEN
        ALTER TABLE events RENAME COLUMN inquiry_number TO inqury_number;
    END IF;
END $$;

ALTER TABLE events ALTER COLUMN event_id DROP IDENTITY IF EXISTS;
ALTER TABLE events ALTER COLUMN event_id TYPE bigint;
ALTER TABLE events ALTER COLUMN category_seq TYPE bigint;
ALTER TABLE events ALTER COLUMN gu_seq TYPE bigint;
ALTER TABLE events ALTER COLUMN category_seq DROP NOT NULL;
ALTER TABLE events ALTER COLUMN gu_seq DROP NOT NULL;
ALTER TABLE events ALTER COLUMN event_name DROP NOT NULL;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'events' AND column_name = 'reg_date' AND data_type = 'text'
    ) THEN
        ALTER TABLE events ALTER COLUMN reg_date TYPE timestamptz USING NULLIF(reg_date, '')::timestamptz;
    END IF;
END $$;
COMMENT ON TABLE events IS '행사 데이터';

ALTER TABLE category ALTER COLUMN category_id TYPE bigint;
ALTER TABLE category ALTER COLUMN category_name TYPE text;
ALTER TABLE gu ALTER COLUMN gu_id TYPE bigint;
ALTER TABLE gu ALTER COLUMN gu_name TYPE varchar;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'category' AND column_name = 'category_id' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'gu' AND column_name = 'gu_id' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE gu ALTER COLUMN gu_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

SELECT setval(pg_get_serial_sequence('category', 'category_id'), COALESCE((SELECT MAX(category_id) FROM category), 1), true);
SELECT setval(pg_get_serial_sequence('gu', 'gu_id'), COALESCE((SELECT MAX(gu_id) FROM gu), 1), true);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_category_seq_fkey') THEN
        ALTER TABLE events
            ADD CONSTRAINT events_category_seq_fkey
            FOREIGN KEY (category_seq) REFERENCES category(category_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_gu_seq_fkey') THEN
        ALTER TABLE events
            ADD CONSTRAINT events_gu_seq_fkey
            FOREIGN KEY (gu_seq) REFERENCES gu(gu_id);
    END IF;
END $$;
